# Generated by Django 5.2 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_photo",
            field=models.ImageField(blank=True, null=True, upload_to="event-photos/"),
        ),
    ]
