# Generated by Django 5.2 on 2025-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_event_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
