# Generated by Django 5.2 on 2025-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_event_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_photo",
            field=models.ImageField(
                blank=True, default="uncc.png", null=True, upload_to="event-photos/"
            ),
        ),
    ]
